from __future__ import annotations


RECORDS_STYLE = r"""
#panel-records .panel-head{margin-bottom:12px}
#recordsV2{display:grid;gap:12px}
.records-summary{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:8px}
.records-summary-card{position:relative;overflow:hidden;padding:14px;border:1px solid var(--line);border-radius:19px;background:var(--surface);box-shadow:var(--shadow2);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.records-summary-card:after{content:"";position:absolute;width:90px;height:90px;right:-34px;top:-38px;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--record-accent,var(--primary)) 20%,transparent),transparent 70%)}
.records-summary-label{position:relative;z-index:1;font-size:8px;color:var(--muted);font-weight:760}
.records-summary-value{position:relative;z-index:1;margin-top:5px;font-size:20px;line-height:1;font-weight:870;letter-spacing:-.04em}
.records-summary-foot{position:relative;z-index:1;margin-top:5px;font-size:8px;color:var(--muted)}
.records-controls{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:8px;border:1px solid var(--line);border-radius:19px;background:var(--surface);box-shadow:var(--shadow2);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.records-source-tabs,.records-status-tabs{display:flex;align-items:center;gap:5px;min-width:0}
.records-tab{min-height:35px;padding:0 12px;border:0;border-radius:12px;background:transparent;color:var(--muted);font-size:9px;font-weight:790;white-space:nowrap;transition:.18s}
.records-tab.active{color:var(--primary);background:var(--primary-soft);box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--primary) 12%,transparent)}
.records-tab .tab-count{display:inline-grid;place-items:center;min-width:18px;height:18px;margin-left:4px;padding:0 5px;border-radius:99px;background:color-mix(in srgb,var(--muted) 11%,transparent);font-size:7px}
.records-filter-select{min-height:35px;max-width:150px;padding:0 30px 0 11px;border:1px solid var(--line);border-radius:12px;background:var(--soft);font-size:9px;font-weight:730;outline:none}
.records-groups{display:grid;gap:12px}
.record-group{padding:15px;border:1px solid var(--line);border-radius:23px;background:var(--surface);box-shadow:var(--shadow);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.record-group-head{display:flex;align-items:center;justify-content:space-between;gap:10px;margin-bottom:10px}
.record-group-title{display:flex;align-items:center;gap:9px}.record-group-icon{width:36px;height:36px;border-radius:13px;display:grid;place-items:center;color:#fff;font-size:9px;font-weight:880;box-shadow:0 8px 18px color-mix(in srgb,var(--group-accent) 24%,transparent);background:linear-gradient(145deg,var(--group-accent),color-mix(in srgb,var(--group-accent) 72%,#fff))}
.record-group-title h3{margin:0;font-size:14px;letter-spacing:-.025em}.record-group-title p{margin:2px 0 0;font-size:8px;color:var(--muted)}
.record-group-count{display:inline-flex;align-items:center;justify-content:center;min-height:26px;padding:0 9px;border-radius:99px;background:color-mix(in srgb,var(--group-accent) 11%,var(--soft));color:var(--group-accent);font-size:8px;font-weight:800}
.record-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}
.record-v2{position:relative;overflow:hidden;min-width:0;padding:13px;border:1px solid var(--line);border-radius:18px;background:linear-gradient(145deg,color-mix(in srgb,var(--solid) 92%,var(--record-accent-soft)),var(--soft));transition:transform .18s,border-color .18s,box-shadow .18s}
.record-v2:hover{transform:translateY(-1px);border-color:color-mix(in srgb,var(--record-accent) 28%,var(--line));box-shadow:0 10px 24px color-mix(in srgb,var(--record-accent) 10%,transparent)}
.record-v2:before{content:"";position:absolute;left:0;top:12px;bottom:12px;width:3px;border-radius:0 99px 99px 0;background:var(--record-accent)}
.record-v2.ai{--record-accent:#765ff6;--record-accent-soft:#eeeaff}.record-v2.native{--record-accent:#3185d8;--record-accent-soft:#e9f4ff}
.record-v2-top{display:flex;align-items:flex-start;justify-content:space-between;gap:9px;padding-left:4px}.record-v2-source{display:flex;align-items:center;gap:7px;min-width:0}
.record-source-mark{width:30px;height:30px;flex:0 0 30px;border-radius:11px;display:grid;place-items:center;color:#fff;background:linear-gradient(145deg,var(--record-accent),color-mix(in srgb,var(--record-accent) 72%,#fff));font-size:8px;font-weight:880}
.record-v2-title{font-size:11px;font-weight:830;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.record-v2-sub{font-size:8px;color:var(--muted);margin-top:1px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}
.record-state{min-height:23px;padding:0 8px;border-radius:99px;display:inline-flex;align-items:center;justify-content:center;font-size:8px;font-weight:810;white-space:nowrap}.record-state.pending{color:var(--warn);background:var(--warn-soft)}.record-state.hit{color:var(--good);background:var(--good-soft)}.record-state.miss{color:var(--bad);background:var(--bad-soft)}
.record-v2-main{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px;align-items:end;margin-top:11px;padding-left:4px}.record-rank{font-size:16px;font-weight:880;letter-spacing:-.035em}.record-model{margin-top:2px;font-size:8px;color:var(--muted);white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.record-period{text-align:right;font-size:8px;color:var(--muted)}.record-period strong{display:block;color:var(--text);font-size:10px;margin-top:2px}
.record-balls{display:flex;gap:5px;flex-wrap:wrap;margin-top:10px;padding:9px 9px 9px 13px;border-radius:13px;background:color-mix(in srgb,var(--record-accent-soft) 58%,var(--soft));border:1px solid color-mix(in srgb,var(--record-accent) 10%,var(--line))}.record-ball{width:25px;height:25px;border-radius:9px;display:grid;place-items:center;background:var(--solid);border:1px solid color-mix(in srgb,var(--record-accent) 13%,var(--line));font-size:9px;font-weight:820;box-shadow:0 3px 8px rgba(42,48,72,.04)}
.record-v2-foot{display:flex;align-items:center;justify-content:space-between;gap:8px;margin-top:9px;padding-left:4px;font-size:8px;color:var(--muted)}
.record-detail{margin-top:9px;border-top:1px solid var(--line);padding-top:8px}.record-detail summary{cursor:pointer;color:var(--record-accent);font-size:8px;font-weight:760;list-style:none}.record-detail summary::-webkit-details-marker{display:none}.record-detail p{margin:6px 0 0;color:var(--muted);font-size:8px;line-height:1.65}
.records-empty{padding:34px 16px;text-align:center;border:1px dashed color-mix(in srgb,var(--muted) 24%,var(--line));border-radius:18px;background:var(--soft);color:var(--muted)}.records-empty strong{display:block;color:var(--text);font-size:12px;margin-bottom:4px}
#panel-records .legacy-records-card{display:none!important}
@media(max-width:900px){.records-summary{grid-template-columns:repeat(2,minmax(0,1fr))}.record-grid{grid-template-columns:1fr}}
@media(max-width:620px){.records-controls{align-items:stretch;flex-direction:column;padding:7px}.records-source-tabs,.records-status-tabs{display:grid;grid-template-columns:repeat(3,1fr);width:100%}.records-status-tabs{grid-template-columns:repeat(4,1fr)}.records-tab{padding:0 7px}.records-filter-select{width:100%;max-width:none}.record-group{padding:12px;border-radius:20px}.records-summary-card{padding:12px}.records-summary-value{font-size:18px}.record-v2{padding:12px}.record-v2-main{grid-template-columns:1fr}.record-period{text-align:left;display:flex;gap:5px;align-items:center}.record-period strong{display:inline;margin:0}.record-group-head{align-items:flex-start}}
"""


RECORDS_SCRIPT = r"""
(()=>{
  const esc=value=>String(value??'').replace(/[&<>"']/g,char=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
  const fmt=value=>value?new Date(value).toLocaleString('zh-CN',{hour12:false,month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'时间未知';
  const panel=document.getElementById('panel-records');
  const legacy=document.getElementById('recordsList');
  if(!panel||!legacy)return;
  const legacyCard=legacy.closest('.card');if(legacyCard)legacyCard.classList.add('legacy-records-card');
  const workspace=document.createElement('div');workspace.id='recordsV2';workspace.innerHTML=`<div class="records-summary" id="recordsSummary"></div><div class="records-controls"><div class="records-source-tabs"><button class="records-tab" data-source="ai">云端 AI <span class="tab-count" id="countAi">0</span></button><button class="records-tab" data-source="native">本机云端 <span class="tab-count" id="countNative">0</span></button><button class="records-tab" data-source="all">全部 <span class="tab-count" id="countAll">0</span></button></div><div class="records-status-tabs"><button class="records-tab" data-status="all">全部</button><button class="records-tab" data-status="pending">待开奖</button><button class="records-tab" data-status="hit">命中</button><button class="records-tab" data-status="miss">未中</button></div><select class="records-filter-select" id="recordsLotteryFilter"><option value="all">全部彩种</option></select></div><div class="records-groups" id="recordsGroups"><div class="records-empty"><strong>正在读取预测档案</strong>请稍候</div></div>`;
  panel.querySelector('.panel-head').insertAdjacentElement('afterend',workspace);
  let records=[],source=localStorage.getItem('tianji-record-source')||'ai',status=localStorage.getItem('tianji-record-status')||'all',lottery='all';
  const stateOf=record=>record.top6_hit===true?'hit':record.top6_hit===false?'miss':'pending';
  const stateLabel=value=>value==='hit'?'命中':value==='miss'?'未中':'待开奖';
  const rate=items=>{const settled=items.filter(item=>item.top6_hit!==null&&item.top6_hit!==undefined);if(!settled.length)return'暂无结算';const hits=settled.filter(item=>item.top6_hit===true).length;return Math.round(hits/settled.length*100)+'% 命中';};
  function renderSummary(){const ai=records.filter(item=>item.source==='ai'),native=records.filter(item=>item.source!=='ai'),pending=records.filter(item=>stateOf(item)==='pending').length,settled=records.length-pending;document.getElementById('recordsSummary').innerHTML=`<article class="records-summary-card" style="--record-accent:#765ff6"><div class="records-summary-label">云端 AI 档案</div><div class="records-summary-value">${ai.length}</div><div class="records-summary-foot">${rate(ai)}</div></article><article class="records-summary-card" style="--record-accent:#3185d8"><div class="records-summary-label">本机云端档案</div><div class="records-summary-value">${native.length}</div><div class="records-summary-foot">${rate(native)}</div></article><article class="records-summary-card" style="--record-accent:var(--good)"><div class="records-summary-label">已完成结算</div><div class="records-summary-value">${settled}</div><div class="records-summary-foot">命中与未中均已记录</div></article><article class="records-summary-card" style="--record-accent:var(--warn)"><div class="records-summary-label">等待开奖</div><div class="records-summary-value">${pending}</div><div class="records-summary-foot">开奖后自动完成验证</div></article>`;document.getElementById('countAi').textContent=ai.length;document.getElementById('countNative').textContent=native.length;document.getElementById('countAll').textContent=records.length;}
  function card(record){const isAi=record.source==='ai',state=stateOf(record),analysis=[record.analysis,record.risk_note].filter(Boolean).join(' · ');return `<article class="record-v2 ${isAi?'ai':'native'}"><div class="record-v2-top"><div class="record-v2-source"><span class="record-source-mark">${isAi?'AI':'本机'}</span><div><div class="record-v2-title">${esc(record.lottery_name)}</div><div class="record-v2-sub">${isAi?'云端 AI 正式档案':'本机云端统计档案'}</div></div></div><span class="record-state ${state}">${stateLabel(state)}</span></div><div class="record-v2-main"><div><div class="record-rank">第 ${Number(record.position)+1} 名</div><div class="record-model">${esc(record.model||'未知模型')}</div></div><div class="record-period">目标期<strong>${esc(record.target_period)}</strong></div></div><div class="record-balls">${(record.top6||[]).map(number=>`<span class="record-ball">${number}</span>`).join('')}</div><div class="record-v2-foot"><span>训练截止 ${esc(record.trained_through_period||'—')}</span><span>${fmt(record.created_at_epoch_ms)}</span></div>${analysis?`<details class="record-detail"><summary>查看分析说明</summary><p>${esc(analysis)}</p></details>`:''}</article>`;}
  function group(kind,items){const ai=kind==='ai';return `<section class="record-group" style="--group-accent:${ai?'#765ff6':'#3185d8'}"><div class="record-group-head"><div class="record-group-title"><span class="record-group-icon">${ai?'AI':'本机'}</span><div><h3>${ai?'云端 AI 档案':'本机云端档案'}</h3><p>${ai?'由当前服务端 AI 模型首次冻结':'由服务器本机统计算法首次冻结'}</p></div></div><span class="record-group-count">${items.length} 条</span></div><div class="record-grid">${items.length?items.map(card).join(''):`<div class="records-empty"><strong>这里还没有记录</strong>${ai?'等待下一次 AI 成功冻结':'等待下一次本机统计预测'}</div>`}</div></section>`;}
  function render(){document.querySelectorAll('[data-source]').forEach(button=>button.classList.toggle('active',button.dataset.source===source));document.querySelectorAll('[data-status]').forEach(button=>button.classList.toggle('active',button.dataset.status===status));const filtered=records.filter(item=>(lottery==='all'||item.lottery===lottery)&&(status==='all'||stateOf(item)===status));const ai=filtered.filter(item=>item.source==='ai'),native=filtered.filter(item=>item.source!=='ai');document.getElementById('recordsGroups').innerHTML=source==='ai'?group('ai',ai):source==='native'?group('native',native):group('ai',ai)+group('native',native);}
  async function loadRecords(){try{const response=await fetch('/admin/api/state',{cache:'no-store'});if(response.status===401){location.href='/admin';return}if(!response.ok)throw new Error('读取失败');const data=await response.json();records=Array.isArray(data.records)?data.records:[];const select=document.getElementById('recordsLotteryFilter'),current=select.value||lottery,names=[...new Map(records.map(item=>[item.lottery,item.lottery_name])).entries()];select.innerHTML='<option value="all">全部彩种</option>'+names.map(([key,name])=>`<option value="${esc(key)}">${esc(name)}</option>`).join('');lottery=names.some(([key])=>key===current)?current:'all';select.value=lottery;renderSummary();render()}catch(error){document.getElementById('recordsGroups').innerHTML='<div class="records-empty"><strong>档案读取失败</strong>请稍后刷新页面</div>'}}
  document.querySelectorAll('[data-source]').forEach(button=>button.addEventListener('click',()=>{source=button.dataset.source;localStorage.setItem('tianji-record-source',source);render()}));document.querySelectorAll('[data-status]').forEach(button=>button.addEventListener('click',()=>{status=button.dataset.status;localStorage.setItem('tianji-record-status',status);render()}));document.getElementById('recordsLotteryFilter').addEventListener('change',event=>{lottery=event.target.value;render()});loadRecords();setInterval(loadRecords,30000);
})();
"""


def enhance_admin_html(html: str) -> str:
    payload = f"<style>{RECORDS_STYLE}</style><script>{RECORDS_SCRIPT}</script>"
    return html.replace("</body>", payload + "</body>", 1)
