from __future__ import annotations

from html import escape


STYLE = r"""
:root{
  color-scheme:light;--bg:#f4f6fb;--bg2:#edf1f8;--surface:rgba(255,255,255,.88);
  --solid:#fff;--soft:#f5f7fc;--text:#171a25;--text2:#3e4353;--muted:#788095;
  --line:rgba(25,31,49,.09);--primary:#6958f5;--primary2:#965fff;--primary-soft:#eeebff;
  --good:#14845d;--good-soft:#e8f8f1;--warn:#a76700;--warn-soft:#fff4dc;
  --bad:#c33a51;--bad-soft:#fff0f3;--shadow:0 18px 52px rgba(41,47,73,.10);
  --shadow2:0 9px 26px rgba(41,47,73,.07);--safe:max(10px,env(safe-area-inset-bottom))
}
[data-theme="dark"]{
  color-scheme:dark;--bg:#101219;--bg2:#161925;--surface:rgba(28,31,43,.88);--solid:#1b1e29;
  --soft:#232735;--text:#f3f4f8;--text2:#d9dce7;--muted:#9ba2b5;--line:rgba(255,255,255,.08);
  --primary:#988aff;--primary2:#c18cff;--primary-soft:#2d2952;--good:#59d6a4;--good-soft:#173a30;
  --warn:#f3bb63;--warn-soft:#3c301b;--bad:#ff8799;--bad-soft:#43242c;--shadow:0 22px 60px rgba(0,0,0,.28);--shadow2:0 11px 30px rgba(0,0,0,.20)
}
*{box-sizing:border-box}html{-webkit-text-size-adjust:100%;text-size-adjust:100%;scroll-behavior:smooth}
body{margin:0;min-height:100vh;color:var(--text);font:13px/1.55 ui-sans-serif,system-ui,-apple-system,"Segoe UI","Noto Sans SC",sans-serif;background:radial-gradient(circle at 8% -8%,color-mix(in srgb,var(--primary) 15%,transparent),transparent 32%),radial-gradient(circle at 105% 4%,color-mix(in srgb,var(--primary2) 11%,transparent),transparent 30%),linear-gradient(180deg,var(--bg),var(--bg2))}
button,input,select{font:inherit;color:inherit}button{cursor:pointer}a{color:inherit}.shell{width:min(1120px,calc(100% - 24px));margin:auto;padding:10px 0 70px}
.topbar{position:sticky;top:0;z-index:50;display:flex;align-items:center;justify-content:space-between;gap:12px;min-height:62px;padding:9px 2px;margin-bottom:13px;background:linear-gradient(180deg,color-mix(in srgb,var(--bg) 95%,transparent) 72%,transparent);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}
.brand{display:flex;align-items:center;gap:10px;min-width:0}.mark{width:39px;height:39px;flex:0 0 39px;border-radius:14px;display:grid;place-items:center;color:#fff;background:linear-gradient(145deg,var(--primary),var(--primary2));box-shadow:0 10px 24px color-mix(in srgb,var(--primary) 28%,transparent)}.mark svg{width:21px;height:21px}.brand h1{font-size:17px;line-height:1.15;margin:0;font-weight:820;letter-spacing:-.02em}.brand p{font-size:10px;color:var(--muted);margin:3px 0 0;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.toolbar{display:flex;gap:7px;align-items:center}.icon-btn{width:39px;height:39px;border:1px solid var(--line);border-radius:14px;background:var(--surface);display:grid;place-items:center;box-shadow:var(--shadow2);backdrop-filter:blur(16px)}.icon-btn svg{width:18px;height:18px}.status{display:flex;align-items:center;gap:7px;min-height:39px;padding:0 12px;border:1px solid var(--line);border-radius:14px;background:var(--surface);color:var(--muted);box-shadow:var(--shadow2)}.dot{width:8px;height:8px;border-radius:50%;background:var(--good);box-shadow:0 0 0 5px color-mix(in srgb,var(--good) 14%,transparent)}
.hero,.card,.metric,.lottery-card{border:1px solid var(--line);background:var(--surface);box-shadow:var(--shadow);backdrop-filter:blur(18px);-webkit-backdrop-filter:blur(18px)}.hero{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:18px;align-items:end;padding:25px;border-radius:27px;overflow:hidden;position:relative}.hero:after{content:"";position:absolute;width:240px;height:240px;right:-85px;top:-120px;border-radius:50%;background:radial-gradient(circle,color-mix(in srgb,var(--primary) 20%,transparent),transparent 68%)}.hero-copy,.hero-actions{position:relative;z-index:1}.eyebrow{font-size:10px;font-weight:820;letter-spacing:.14em;text-transform:uppercase;color:var(--primary)}.hero h2{font-size:clamp(27px,4.5vw,45px);line-height:1.09;letter-spacing:-.045em;margin:9px 0 10px}.hero p{max-width:680px;margin:0;color:var(--muted);font-size:13px}.hero-actions,.actions{display:flex;gap:8px;flex-wrap:wrap}.btn{min-height:41px;padding:0 14px;border:0;border-radius:14px;display:inline-flex;align-items:center;justify-content:center;gap:7px;font-size:12px;font-weight:760;text-decoration:none}.btn.primary{color:#fff;background:linear-gradient(135deg,var(--primary),var(--primary2));box-shadow:0 11px 25px color-mix(in srgb,var(--primary) 24%,transparent)}.btn.secondary{background:var(--soft);border:1px solid var(--line)}.btn.danger{background:var(--bad-soft);color:var(--bad);border:1px solid color-mix(in srgb,var(--bad) 18%,var(--line))}.btn:disabled{opacity:.55;cursor:not-allowed}.section{margin-top:15px}.section-head,.panel-head,.card-head{display:flex;align-items:flex-end;justify-content:space-between;gap:12px}.section-head{margin:0 2px 9px}.section-head h2,.panel-head h2,.card-head h3{margin:0;letter-spacing:-.03em}.section-head h2{font-size:18px}.panel-head h2{font-size:25px}.card-head h3{font-size:15px}.section-head p,.panel-head p,.card-head p{color:var(--muted);margin:3px 0 0;font-size:10px}.metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:10px}.metric{padding:15px;border-radius:20px;box-shadow:var(--shadow2)}.metric-label{font-size:10px;color:var(--muted)}.metric-value{font-size:18px;font-weight:820;letter-spacing:-.025em;margin-top:8px;overflow-wrap:anywhere}.metric-foot{font-size:9px;color:var(--muted);margin-top:3px}.good{color:var(--good)}.warn{color:var(--warn)}.bad{color:var(--bad)}
.lottery-grid,.overview-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:12px}.lottery-card{border-radius:25px;overflow:hidden}.lottery-main,.overview-card{padding:19px}.lottery-title{display:flex;justify-content:space-between;align-items:flex-start;gap:10px}.lottery-title h3{font-size:20px;margin:0;letter-spacing:-.03em}.sub{font-size:10px;color:var(--muted);line-height:1.55}.target{flex:0 0 auto;padding:8px 10px;border-radius:14px;background:var(--soft);border:1px solid var(--line);font-size:9px;color:var(--muted);text-align:right}.target strong{display:block;color:var(--text);font-size:12px;margin-top:2px}.numbers{display:grid;grid-template-columns:repeat(10,minmax(0,1fr));gap:5px;margin:15px 0}.number{aspect-ratio:1;border-radius:11px;display:grid;place-items:center;background:var(--soft);border:1px solid var(--line);font-size:12px;font-weight:820}.ai-strip{display:flex;align-items:center;justify-content:space-between;gap:10px;padding:11px 12px;border-radius:14px;background:var(--soft);border:1px solid var(--line)}.ai-title{font-size:11px;font-weight:760}.badge{display:inline-flex;align-items:center;justify-content:center;min-height:24px;padding:0 8px;border-radius:999px;font-size:9px;font-weight:780;background:var(--primary-soft);color:var(--primary)}.badge.good{background:var(--good-soft);color:var(--good)}.badge.warn{background:var(--warn-soft);color:var(--warn)}.badge.bad{background:var(--bad-soft);color:var(--bad)}.forecasts{border-top:1px solid var(--line)}.forecast{padding:13px 19px;border-top:1px solid var(--line)}.forecast:first-child{border-top:0}.forecast-head{display:flex;justify-content:space-between;gap:10px;font-size:11px;font-weight:760}.balls{display:flex;gap:5px;flex-wrap:wrap;margin-top:7px}.ball{min-width:24px;height:24px;padding:0 5px;border-radius:8px;display:grid;place-items:center;background:var(--soft);border:1px solid var(--line);font-size:10px;font-weight:760}.empty{padding:22px;text-align:center;color:var(--muted);font-size:11px}.disclaimer{margin-top:15px;padding:13px 16px;text-align:center;color:var(--muted);font-size:10px;background:var(--soft);border:1px solid var(--line);border-radius:17px}
.layout{display:grid;grid-template-columns:210px minmax(0,1fr);gap:15px}.sidebar{position:sticky;top:72px;height:max-content;padding:9px;border-radius:21px;background:var(--surface);border:1px solid var(--line);box-shadow:var(--shadow2);backdrop-filter:blur(18px)}.side-label{padding:8px 10px 5px;font-size:9px;letter-spacing:.13em;text-transform:uppercase;color:var(--muted)}.nav-btn{width:100%;min-height:43px;border:0;border-radius:13px;padding:0 11px;display:flex;align-items:center;gap:9px;background:transparent;color:var(--muted);font-size:12px;font-weight:720;text-align:left}.nav-btn svg{width:17px;height:17px}.nav-btn.active{color:var(--primary);background:var(--primary-soft)}.nav-tail{margin-left:auto;font-size:8px}.content{min-width:0}.panel{display:none}.panel.active{display:block}.panel-head{margin-bottom:11px}.card{border-radius:25px}.card-pad{padding:19px}.card+.card{margin-top:12px}.card-head{margin-bottom:12px}
.switch-row{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:14px;border-radius:17px;background:linear-gradient(135deg,var(--primary-soft),var(--soft));border:1px solid color-mix(in srgb,var(--primary) 15%,var(--line))}.switch-copy strong{font-size:12px}.switch-copy div{font-size:9px;color:var(--muted);margin-top:2px}.switch{position:relative;width:48px;height:28px;flex:0 0 48px}.switch input{opacity:0;width:0;height:0}.slider{position:absolute;inset:0;border-radius:99px;background:#c8cdda;transition:.18s}.slider:before{content:"";position:absolute;width:22px;height:22px;left:3px;top:3px;border-radius:50%;background:#fff;box-shadow:0 3px 9px rgba(0,0,0,.18);transition:.18s}.switch input:checked+.slider{background:var(--primary)}.switch input:checked+.slider:before{transform:translateX(20px)}
.profile-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.profile-card{position:relative;padding:13px;border-radius:17px;background:var(--soft);border:1px solid var(--line);transition:.18s}.profile-card.active{border-color:color-mix(in srgb,var(--primary) 45%,var(--line));background:linear-gradient(135deg,var(--primary-soft),var(--soft));box-shadow:0 8px 22px color-mix(in srgb,var(--primary) 10%,transparent)}.profile-card.selected{outline:3px solid color-mix(in srgb,var(--primary) 12%,transparent)}.profile-top{display:flex;justify-content:space-between;gap:8px}.profile-name{font-size:12px;font-weight:800}.profile-model{font-size:10px;color:var(--text2);margin-top:3px;overflow-wrap:anywhere}.profile-endpoint{font-size:9px;color:var(--muted);margin-top:7px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.profile-actions{display:flex;gap:6px;margin-top:9px}.mini-btn{min-height:30px;padding:0 9px;border-radius:10px;border:1px solid var(--line);background:var(--solid);font-size:9px;font-weight:720}.mini-btn.primary{background:var(--primary);color:#fff;border-color:transparent}.notice{padding:12px 13px;border-radius:15px;background:var(--primary-soft);color:color-mix(in srgb,var(--primary) 72%,var(--text));font-size:10px;line-height:1.65}.form-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:11px}.field{display:flex;flex-direction:column;gap:6px}.field.full{grid-column:1/-1}.field label{font-size:10px;color:var(--muted);font-weight:720}.input{width:100%;min-height:44px;padding:0 12px;border-radius:14px;border:1px solid var(--line);background:var(--soft);outline:none;overflow:hidden;text-overflow:ellipsis}.input:focus{border-color:color-mix(in srgb,var(--primary) 55%,var(--line));box-shadow:0 0 0 4px color-mix(in srgb,var(--primary) 10%,transparent);background:var(--solid)}.chips{display:flex;gap:7px;flex-wrap:wrap}.chip{min-height:32px;padding:0 10px;border-radius:999px;border:1px solid var(--line);background:var(--soft);color:var(--muted);font-size:9px;font-weight:720}.result{min-height:72px;padding:13px;border-radius:16px;background:#151823;color:#e4e8f5;font:10px/1.65 ui-monospace,SFMono-Regular,Menlo,monospace;white-space:pre-wrap;word-break:break-word}.result.success{background:#12352a;color:#d0f8e7}.result.error{background:#43222b;color:#ffe0e5}
.task-grid,.diag-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:9px}.task,.diag{padding:13px;border-radius:17px;background:var(--soft);border:1px solid var(--line)}.task-top,.diag-top{display:flex;justify-content:space-between;align-items:center;gap:8px}.task-title,.diag-title{font-size:11px;font-weight:780}.task-body,.diag-body{font-size:10px;color:var(--muted);line-height:1.6;margin-top:6px}.task-time{font-size:9px;color:var(--muted);margin-top:6px}.archive-list{display:grid;gap:8px}.archive{display:grid;grid-template-columns:minmax(105px,.8fr) minmax(130px,1fr) minmax(140px,1.3fr) auto;gap:10px;align-items:center;padding:12px 13px;border-radius:16px;background:var(--soft);border:1px solid var(--line)}.archive-title{font-size:11px;font-weight:780}.archive-sub{font-size:9px;color:var(--muted);margin-top:2px}.archive-picks{font-size:10px;color:var(--text2)}
.mobile-nav{display:none}.toast{position:fixed;right:14px;bottom:calc(14px + env(safe-area-inset-bottom));z-index:100;max-width:min(400px,calc(100% - 28px));padding:12px 14px;border-radius:14px;background:#171a25;color:#fff;box-shadow:0 18px 45px rgba(0,0,0,.28);font-size:11px;opacity:0;transform:translateY(10px);pointer-events:none;transition:.18s}.toast.show{opacity:1;transform:none}.toast.error{background:#772638}.login-wrap{min-height:100vh;display:grid;place-items:center;padding:20px}.login-card{width:min(410px,100%);padding:24px;border-radius:28px;background:var(--surface);border:1px solid var(--line);box-shadow:var(--shadow);backdrop-filter:blur(20px)}.login-head{display:flex;align-items:center;gap:11px;margin-bottom:18px}.login-card h1{font-size:22px;margin:0}.login-card p{font-size:11px;color:var(--muted)}.login-card .btn{width:100%;margin-top:11px}.login-foot{text-align:center;margin-top:15px;font-size:10px;color:var(--primary)}
@media(max-width:880px){.metrics{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:180px minmax(0,1fr)}.numbers{grid-template-columns:repeat(5,1fr)}.archive{grid-template-columns:1fr 1fr}.archive-picks{grid-column:1/-1}}
@media(max-width:720px){body{font-size:12px}.shell{width:min(100% - 16px,680px);padding-top:4px;padding-bottom:94px}.topbar{min-height:54px;padding:6px 0;margin-bottom:9px}.mark{width:36px;height:36px;flex-basis:36px;border-radius:13px}.brand h1{font-size:16px}.brand p,.status.hide-mobile{display:none}.icon-btn{width:37px;height:37px}.hero{grid-template-columns:1fr;padding:20px}.hero h2{font-size:28px}.hero p{font-size:11px}.hero-actions{justify-content:flex-start}.lottery-grid,.overview-grid,.task-grid,.diag-list,.profile-grid{grid-template-columns:1fr}.layout{display:block}.sidebar{display:none}.mobile-nav{display:grid;grid-template-columns:repeat(4,1fr);position:fixed;left:8px;right:8px;bottom:var(--safe);z-index:80;padding:5px;border-radius:20px;background:color-mix(in srgb,var(--solid) 90%,transparent);border:1px solid var(--line);box-shadow:0 15px 42px rgba(29,34,54,.22);backdrop-filter:blur(22px);-webkit-backdrop-filter:blur(22px)}.mobile-nav .nav-btn{min-height:52px;flex-direction:column;justify-content:center;gap:2px;padding:0;font-size:8px}.mobile-nav .nav-btn svg{width:17px;height:17px}.mobile-nav .nav-tail{display:none}.panel-head{align-items:flex-start;flex-direction:column}.form-grid{grid-template-columns:1fr}.field.full{grid-column:auto}.toast{bottom:calc(78px + var(--safe))}.card-pad{padding:16px}.profile-card{padding:12px}}
@media(max-width:430px){.toolbar{gap:5px}.hero-actions{width:100%}.hero-actions .btn{flex:1}.metric{padding:13px}.metric-value{font-size:16px}.lottery-main,.overview-card{padding:16px}.lottery-title h3{font-size:18px}.forecast{padding:12px 16px}.panel-head h2{font-size:22px}.actions .btn{flex:1}.actions .btn.danger{flex:0 0 100%}}
@media(prefers-reduced-motion:reduce){*{scroll-behavior:auto!important;transition:none!important}}
"""


ICONS = {
    "spark": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3l1.2 3.8L17 8l-3.8 1.2L12 13l-1.2-3.8L7 8l3.8-1.2L12 3Z"/><path d="M18 14l.8 2.4 2.2.6-2.2.8-.8 2.2-.8-2.2-2.2-.8 2.2-.6.8-2.4Z"/></svg>',
    "sun": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><circle cx="12" cy="12" r="4"/><path d="M12 2v2M12 20v2M4.9 4.9l1.4 1.4M17.7 17.7l1.4 1.4M2 12h2M20 12h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>',
    "refresh": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M20 11a8 8 0 1 0-2.4 5.7"/><path d="M20 4v7h-7"/></svg>',
    "dashboard": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8"><rect x="3" y="3" width="7" height="7" rx="2"/><rect x="14" y="3" width="7" height="7" rx="2"/><rect x="3" y="14" width="7" height="7" rx="2"/><rect x="14" y="14" width="7" height="7" rx="2"/></svg>',
    "brain": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M10 4a3 3 0 0 0-4 3 3 3 0 0 0-1 5 3 3 0 0 0 2 5 3 3 0 0 0 5 2V5a3 3 0 0 0-2-1Z"/><path d="M14 4a3 3 0 0 1 4 3 3 3 0 0 1 1 5 3 3 0 0 1-2 5 3 3 0 0 1-5 2V5a3 3 0 0 1 2-1Z"/></svg>',
    "archive": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M4 7h16v13H4zM3 3h18v4H3zM9 11h6"/></svg>',
    "shield": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round"><path d="M12 3 20 6v5c0 5-3.4 8.4-8 10-4.6-1.6-8-5-8-10V6l8-3Z"/><path d="m9 12 2 2 4-4"/></svg>',
    "logout": '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round"><path d="M10 5H5v14h5M14 8l4 4-4 4M18 12H9"/></svg>',
}


def _icon(name: str) -> str:
    return ICONS[name]


def _document(title: str, body: str, script: str = "") -> str:
    theme = r"""
const root=document.documentElement;const saved=localStorage.getItem('tianji-theme');const dark=window.matchMedia&&window.matchMedia('(prefers-color-scheme:dark)').matches;root.dataset.theme=saved||(dark?'dark':'light');function toggleTheme(){root.dataset.theme=root.dataset.theme==='dark'?'light':'dark';localStorage.setItem('tianji-theme',root.dataset.theme)}
"""
    return f'<!doctype html><html lang="zh-CN" data-theme="light"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#f4f6fb"><title>{escape(title)}</title><style>{STYLE}</style></head><body>{body}<div class="toast" id="toast"></div><script>{theme}</script><script>{script}</script></body></html>'


def public_page() -> str:
    body = f"""
<div class="shell"><header class="topbar"><div class="brand"><div class="mark">{_icon('spark')}</div><div><h1>天机云端</h1><p>前向冻结 · 自动结算 · 本地兜底</p></div></div><div class="toolbar"><div class="status hide-mobile"><span class="dot" id="statusDot"></span><span id="statusText">连接中</span></div><button class="icon-btn" onclick="toggleTheme()">{_icon('sun')}</button><button class="icon-btn" id="refreshBtn">{_icon('refresh')}</button></div></header>
<section class="hero"><div class="hero-copy"><div class="eyebrow">Tianji Cloud</div><h2>云端负责持续运行，<br>手机始终保留本地能力。</h2><p>服务器同步开奖并保存首次冻结的本机与 AI 结果。服务器停机后，Android 仍可继续使用本机统计、历史数据和手机直连 AI。</p></div><div class="hero-actions"><a class="btn primary" href="/admin">管理控制台</a><a class="btn secondary" href="/docs">API 文档</a></div></section>
<section class="section"><div class="section-head"><div><h2>运行状态</h2><p>页面每 30 秒自动刷新。</p></div><span class="sub" id="lastRefresh">—</span></div><div class="metrics" id="metrics"></div></section>
<section class="section"><div class="section-head"><div><h2>实时预测</h2><p>每个目标期仅保留最早冻结的正式结果。</p></div></div><div class="lottery-grid" id="lotteries"></div></section><div class="disclaimer">随机开奖不可可靠预测。本服务仅用于统计实验、首次冻结与目标期验证，不承诺盈利或必中。</div></div>
"""
    script = r"""
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>n?new Date(n).toLocaleString('zh-CN',{hour12:false}):'—';
const jobs={queued:['排队中','warn'],running:['分析中','warn'],completed:['已冻结','good'],duplicate:['已冻结','good'],error:['调用失败','bad'],discarded:['封盘丢弃','bad'],skipped:['等待下期','warn']};const job=j=>j?(jobs[j.status]||['等待调度','warn']):['等待调度','warn'];
function card(x){const j=job(x.ai_job),fs=(x.forecasts||[]).map(f=>`<div class="forecast"><div class="forecast-head"><span>${f.source==='ai'?'云端 AI':'本机云端'} · 第 ${f.position+1} 名</span><span class="badge ${f.top6_hit===true?'good':f.top6_hit===false?'bad':'warn'}">${f.top6_hit===true?'命中':f.top6_hit===false?'未中':'待开奖'}</span></div><div class="balls">${f.top6.map(n=>`<span class="ball">${n}</span>`).join('')}</div><div class="sub" style="margin-top:6px">${esc(f.model)} · 目标期 ${esc(f.target_period)}</div></div>`).join('');return `<article class="lottery-card"><div class="lottery-main"><div class="lottery-title"><div><h3>${esc(x.name)}</h3><div class="sub">最新期 ${esc(x.latest_period||'等待同步')} · ${fmt(x.synced_at_epoch_ms)}</div></div><div class="target">目标期<strong>${esc(x.next_period||'待同步')}</strong></div></div><div class="numbers">${(x.numbers||[]).map(n=>`<span class="number">${n}</span>`).join('')}</div><div class="ai-strip"><div><div class="ai-title">AI 自动任务</div><div class="sub">${esc((x.ai_job&&x.ai_job.model)||'等待配置')}</div></div><span class="badge ${j[1]}">${j[0]}</span></div></div><div class="forecasts">${fs||'<div class="empty">等待下一期前向档案</div>'}</div></article>`}
async function refresh(){try{const r=await fetch('/v1/public/overview',{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();$('statusText').textContent=d.health.status==='ok'?'运行正常':'状态异常';$('statusDot').style.background=d.health.status==='ok'?'var(--good)':'var(--bad)';$('lastRefresh').textContent='刷新于 '+new Date().toLocaleTimeString('zh-CN',{hour12:false});$('metrics').innerHTML=`<div class="metric"><div class="metric-label">服务版本</div><div class="metric-value">${esc(d.health.version)}</div><div class="metric-foot">API ${esc(d.health.status)}</div></div><div class="metric"><div class="metric-label">数据库</div><div class="metric-value ${d.health.database==='ok'?'good':'bad'}">${d.health.database==='ok'?'正常':'异常'}</div><div class="metric-foot">本地前向档案</div></div><div class="metric"><div class="metric-label">后台任务</div><div class="metric-value ${d.health.worker==='ok'?'good':'warn'}">${d.health.worker==='ok'?'运行中':'等待中'}</div><div class="metric-foot">自动同步与结算</div></div><div class="metric"><div class="metric-label">AI 自动预测</div><div class="metric-value">${d.ai.auto_predict?'已开启':'已关闭'}</div><div class="metric-foot">${d.ai.configured?esc(d.ai.profile_name||d.ai.model):'尚未配置模型'} · 共 ${d.ai_profile_count||0} 个</div></div>`;$('lotteries').innerHTML=d.lotteries.map(card).join('')}catch(e){$('statusText').textContent='连接失败';$('statusDot').style.background='var(--bad)'}}$('refreshBtn').onclick=refresh;refresh();setInterval(refresh,30000);
"""
    return _document("天机云端", body, script)


def login_page(configured: bool) -> str:
    disabled = "" if configured else "disabled"
    message = "输入网页管理密码，模型、任务和档案都可在这里管理。" if configured else "服务器尚未设置管理密码，请先完成一次升级初始化。"
    body = f"""
<div class="login-wrap"><main class="login-card"><div class="login-head"><div class="mark">{_icon('spark')}</div><div><h1>天机控制台</h1><p>进入控制台管理云端服务</p></div></div><p>{escape(message)}</p><form id="loginForm"><div class="field"><label>管理密码</label><input class="input" id="password" type="password" minlength="8" autocomplete="current-password" placeholder="输入管理密码" {disabled}></div><button class="btn primary" id="loginBtn" {disabled}>进入控制台</button></form><div class="login-foot"><a href="/">返回公开状态页</a></div></main></div>
"""
    script = r"""
const toast=(m,e=false)=>{const t=document.getElementById('toast');t.textContent=m;t.className='toast show'+(e?' error':'');setTimeout(()=>t.className='toast',2600)};document.getElementById('loginForm').addEventListener('submit',async e=>{e.preventDefault();const b=document.getElementById('loginBtn');b.disabled=true;try{const r=await fetch('/admin/api/login',{method:'POST',headers:{'Content-Type':'application/json','X-Tianji-Admin':'1'},body:JSON.stringify({password:document.getElementById('password').value})});const d=await r.json();if(!r.ok)throw Error(d.detail||'登录失败');location.href='/admin'}catch(x){toast(x.message,true);b.disabled=false}});
"""
    return _document("登录 · 天机控制台", body, script)


def admin_page() -> str:
    nav = f"""<button class="nav-btn active" data-panel="overview">{_icon('dashboard')}<span>总览</span><span class="nav-tail">01</span></button><button class="nav-btn" data-panel="ai">{_icon('brain')}<span>AI 模型</span><span class="nav-tail">02</span></button><button class="nav-btn" data-panel="records">{_icon('archive')}<span>预测档案</span><span class="nav-tail">03</span></button><button class="nav-btn" data-panel="security">{_icon('shield')}<span>设置</span><span class="nav-tail">04</span></button>"""
    body = f"""
<div class="shell"><header class="topbar"><div class="brand"><div class="mark">{_icon('spark')}</div><div><h1>天机控制台</h1><p>模型、任务、档案与安全设置</p></div></div><div class="toolbar"><div class="status hide-mobile"><span class="dot" id="topDot"></span><span id="topStatus">读取中</span></div><button class="icon-btn" onclick="toggleTheme()">{_icon('sun')}</button><button class="icon-btn" id="logoutBtn">{_icon('logout')}</button></div></header>
<div class="layout"><aside class="sidebar"><div class="side-label">Cloud Console</div>{nav}</aside><main class="content">
<section class="panel active" id="panel-overview"><div class="panel-head"><div><h2>运行总览</h2><p>查看开奖同步、自动预测、结算与异常状态。</p></div><button class="btn primary" id="runBtn">立即同步</button></div><div class="metrics" id="adminMetrics"></div><div class="section"><div class="section-head"><div><h2>彩种状态</h2><p>两个彩种独立运行，不互相等待。</p></div></div><div class="overview-grid" id="adminLotteries"></div></div><div class="card card-pad"><div class="card-head"><div><h3>运行诊断</h3><p>全部转换成中文说明，不再显示整屏英文 JSON。</p></div></div><div class="diag-list" id="diagnostics"></div></div></section>
<section class="panel" id="panel-ai"><div class="panel-head"><div><h2>AI 模型</h2><p>可保存多个模型配置，选择一个作为当前云端模型。</p></div><button class="btn secondary" id="newAiBtn">添加模型</button></div><div class="card card-pad"><div class="switch-row"><div class="switch-copy"><strong>AI 自动预测</strong><div>关闭后服务端不再调用 AI，本机云端统计、开奖同步和结算仍继续运行。</div></div><label class="switch"><input id="aiAutoEnabled" type="checkbox"><span class="slider"></span></label></div><div class="notice" style="margin-top:11px">可以保存多个 DeepSeek、OpenAI 或兼容接口。为避免同一期出现多条冲突档案，每期只由“当前模型”生成一条正式 AI 预测。</div></div>
<div class="card card-pad"><div class="card-head"><div><h3>已保存模型</h3><p>点击卡片编辑；点击“设为当前”后从下一期开始使用。</p></div><span class="badge" id="profileCount">0 个</span></div><div class="profile-grid" id="profileList"></div></div>
<div class="card card-pad"><div class="card-head"><div><h3 id="editorTitle">添加模型</h3><p id="editorHint">API Key 分开加密式保存，不会完整回显。</p></div></div><div class="chips" style="margin-bottom:11px"><button class="chip" data-preset="deepseek-pro">DeepSeek V4 Pro</button><button class="chip" data-preset="deepseek-flash">DeepSeek V4 Flash</button><button class="chip" data-preset="deepseek-custom">DeepSeek 自定义</button><button class="chip" data-preset="openai">OpenAI Responses</button></div><div class="form-grid"><div class="field"><label>配置名称</label><input class="input" id="aiProfileName" placeholder="例如：DeepSeek 主力"></div><div class="field"><label>模型名</label><input class="input" id="aiModel" list="modelList" placeholder="选择或输入模型"><datalist id="modelList"></datalist></div><div class="field full"><label>接口地址</label><input class="input" id="aiEndpoint" inputmode="url" placeholder="https://api.example.com/v1/chat/completions"></div><div class="field"><label>超时时间</label><select class="input" id="aiTimeout"><option value="45">45 秒</option><option value="90">90 秒</option><option value="120">120 秒</option><option value="180">180 秒</option><option value="300">300 秒</option></select></div><div class="field"><label>API Key</label><input class="input" id="aiKey" type="password" autocomplete="new-password" placeholder="留空保留现有密钥"></div></div><div class="sub" id="keyHint" style="margin-top:8px">当前密钥：未配置</div><div class="actions" style="margin-top:13px"><button class="btn primary" id="saveAiBtn">保存模型</button><button class="btn secondary" id="activateAiBtn">设为当前</button><button class="btn secondary" id="testAiBtn">真实调用测试</button><button class="btn secondary" id="modelsBtn">读取模型</button><button class="btn danger" id="deleteAiBtn">删除模型</button></div><div class="result" id="aiResult" style="margin-top:12px">等待操作</div></div></section>
<section class="panel" id="panel-records"><div class="panel-head"><div><h2>预测档案</h2><p>查看首次冻结结果、模型来源与目标期结算。</p></div></div><div class="card card-pad"><div class="archive-list" id="recordsList"></div></div></section>
<section class="panel" id="panel-security"><div class="panel-head"><div><h2>设置</h2><p>修改网页登录密码并查看自动更新状态。</p></div></div><div class="card card-pad"><div class="card-head"><div><h3>管理密码</h3><p>不会修改服务器 root 密码。</p></div></div><div class="form-grid"><div class="field"><label>当前管理密码</label><input class="input" id="oldPassword" type="password"></div><div class="field"><label>新管理密码</label><input class="input" id="newPassword" type="password" minlength="8"></div></div><button class="btn primary" id="passwordBtn" style="margin-top:12px">更新密码</button></div><div class="card card-pad"><div class="card-head"><div><h3>云端自动更新</h3><p>每 5 分钟检查主分支，失败自动回滚。</p></div></div><div class="task"><div class="task-top"><span class="task-title">安全自动更新</span><span class="badge good">已启用</span></div><div class="task-body">后端更新前先备份数据库，再构建、健康检查；新版本异常时恢复旧版本。App 单独更新不会重启云端。</div></div></div></section>
</main></div></div><nav class="mobile-nav">{nav}</nav>
"""
    script = r"""
const $=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),fmt=n=>n?new Date(n).toLocaleString('zh-CN',{hour12:false}):'—',ago=n=>{if(!n)return'时间未知';const s=Math.max(0,Math.floor((Date.now()-n)/1000));if(s<60)return s+' 秒前';if(s<3600)return Math.floor(s/60)+' 分钟前';if(s<86400)return Math.floor(s/3600)+' 小时前';return Math.floor(s/86400)+' 天前'};
let state=null,currentProfileId=null;const toast=(m,e=false)=>{const t=$('toast');t.textContent=m;t.className='toast show'+(e?' error':'');setTimeout(()=>t.className='toast',2800)};async function api(path,options={}){const r=await fetch(path,{cache:'no-store',...options,headers:{'X-Tianji-Admin':'1',...(options.headers||{})}});if(r.status===401){location.href='/admin';throw Error('登录已过期')}const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.detail||('HTTP '+r.status));return d}
function panel(name){document.querySelectorAll('.panel').forEach(x=>x.classList.toggle('active',x.id==='panel-'+name));document.querySelectorAll('.nav-btn').forEach(x=>x.classList.toggle('active',x.dataset.panel===name));scrollTo({top:0,behavior:'smooth'})}document.querySelectorAll('.nav-btn').forEach(x=>x.onclick=()=>panel(x.dataset.panel));
const statusMap={queued:['排队中','warn'],running:['分析中','warn'],completed:['已冻结','good'],duplicate:['已冻结','good'],error:['失败','bad'],discarded:['封盘丢弃','bad'],skipped:['等待下期','warn']};const job=j=>j?(statusMap[j.status]||['等待调度','warn']):['等待调度','warn'];
function friendlyError(m){const s=String(m||'').toLowerCase();if(s.includes('401')||s.includes('unauthorized'))return'API Key 无效、已过期，或与当前接口不匹配';if(s.includes('403'))return'接口拒绝访问，请检查账号权限或模型权限';if(s.includes('404'))return'接口地址或模型名不存在';if(s.includes('429'))return'请求过于频繁、余额不足或接口限流';if(s.includes('timeout')||s.includes('timed out'))return'模型响应超时，请提高超时时间或换用更快模型';if(s.includes('封盘'))return'模型返回太晚，目标期已经封盘，结果没有写入档案';return m||'没有发现错误'}
function lotteryCard(x){const j=job(x.ai_job);return `<article class="card overview-card"><div class="lottery-title"><div><h3>${esc(x.name)}</h3><div class="sub">最新期 ${esc(x.latest_period||'等待同步')} · ${fmt(x.synced_at_epoch_ms)}</div></div><div class="target">目标期<strong>${esc(x.next_period||'待同步')}</strong></div></div><div class="numbers">${(x.numbers||[]).map(n=>`<span class="number">${n}</span>`).join('')}</div><div class="ai-strip"><div><div class="ai-title">AI 任务</div><div class="sub">${esc((x.ai_job&&x.ai_job.model)||'等待当前模型')}</div></div><span class="badge ${j[1]}">${j[0]}</span></div></article>`}
function diagnostics(d){const rows=[`<article class="diag"><div class="diag-top"><span class="diag-title">后台工作进程</span><span class="badge ${d.health.worker==='ok'?'good':'warn'}">${d.health.worker==='ok'?'正常':'等待'}</span></div><div class="diag-body">最近心跳：${ago(d.health.last_worker_heartbeat_epoch_ms)}。负责开奖同步、结算和自动预测调度。</div></article>`];d.lotteries.forEach(x=>{const j=job(x.ai_job),msg=x.ai_job&&x.ai_job.message?friendlyError(x.ai_job.message):(d.ai.auto_predict?'等待进入合适的预测窗口':'AI 自动预测已关闭');rows.push(`<article class="diag"><div class="diag-top"><span class="diag-title">${esc(x.name)} · AI</span><span class="badge ${j[1]}">${d.ai.auto_predict?j[0]:'已关闭'}</span></div><div class="diag-body">${esc(msg)}<br>目标期：${esc((x.ai_job&&x.ai_job.target_period)||x.next_period||'—')} · 更新于 ${ago(x.ai_job&&(x.ai_job.updated_at_epoch_ms||x.ai_job.updated_at))}</div></article>`)});Object.entries(d.ai_errors||{}).forEach(([key,e])=>{const lot=d.lotteries.find(x=>x.key===key);rows.push(`<article class="diag"><div class="diag-top"><span class="diag-title">${esc(lot?lot.name:key)} · 历史失败记录</span><span class="badge bad">需留意</span></div><div class="diag-body">${esc(friendlyError(e&&e.message))}<br>记录目标期：${esc((e&&e.target_period)||'—')} · ${ago(e&&(e.completed_at_epoch_ms||e.at))}</div></article>`)});return rows.join('')}
function archive(r){const l=r.top6_hit===true?['命中','good']:r.top6_hit===false?['未中','bad']:['待开奖','warn'];return `<article class="archive"><div><div class="archive-title">${esc(r.lottery_name)}</div><div class="archive-sub">目标期 ${esc(r.target_period)}</div></div><div><div class="archive-title">${r.source==='ai'?'云端 AI':'本机云端'} · 第 ${r.position+1} 名</div><div class="archive-sub">${esc(r.model)}</div></div><div class="archive-picks">六码 ${r.top6.join(' ')}</div><span class="badge ${l[1]}">${l[0]}</span></article>`}
function profiles(reg){$('profileCount').textContent=(reg.profile_count||0)+' 个';const list=reg.profiles||[];$('profileList').innerHTML=list.length?list.map(p=>`<article class="profile-card ${p.active?'active':''} ${p.id===currentProfileId?'selected':''}" data-id="${esc(p.id)}"><div class="profile-top"><div><div class="profile-name">${esc(p.name)}</div><div class="profile-model">${esc(p.model)}</div></div><span class="badge ${p.active?'good':p.ready?'':'warn'}">${p.active?'当前':p.ready?'已配置':'缺少 Key'}</span></div><div class="profile-endpoint">${esc(p.endpoint)}</div><div class="profile-actions"><button class="mini-btn" data-edit="${esc(p.id)}">编辑</button>${p.active?'':`<button class="mini-btn primary" data-use="${esc(p.id)}">设为当前</button>`}</div></article>`).join(''):'<div class="empty">还没有保存模型，点击右上角“添加模型”。</div>';document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();selectProfile(b.dataset.edit)});document.querySelectorAll('[data-use]').forEach(b=>b.onclick=async e=>{e.stopPropagation();await useProfile(b.dataset.use)});document.querySelectorAll('.profile-card[data-id]').forEach(c=>c.onclick=()=>selectProfile(c.dataset.id))}
function clearEditor(){currentProfileId=null;$('editorTitle').textContent='添加模型';$('aiProfileName').value='';$('aiEndpoint').value='';$('aiModel').value='';$('aiTimeout').value='120';$('aiKey').value='';$('keyHint').textContent='当前密钥：未配置';$('activateAiBtn').disabled=true;$('deleteAiBtn').disabled=true;if(state)profiles(state.ai_registry)}
function selectProfile(id){const p=(state.ai_registry.profiles||[]).find(x=>x.id===id);if(!p)return;currentProfileId=id;$('editorTitle').textContent='编辑 '+p.name;$('aiProfileName').value=p.name||'';$('aiEndpoint').value=p.endpoint||'';$('aiModel').value=p.model||'';$('aiTimeout').value=String(p.timeout_seconds||120);$('aiKey').value='';$('keyHint').textContent='当前密钥：'+p.api_key_hint;$('activateAiBtn').disabled=!!p.active;$('deleteAiBtn').disabled=false;profiles(state.ai_registry)}
function render(d){state=d;$('topStatus').textContent=d.health.worker==='ok'?'运行正常':'需要检查';$('topDot').style.background=d.health.worker==='ok'?'var(--good)':'var(--warn)';$('adminMetrics').innerHTML=`<div class="metric"><div class="metric-label">服务版本</div><div class="metric-value">${esc(d.health.version)}</div><div class="metric-foot">API ${d.health.status==='ok'?'正常':'异常'}</div></div><div class="metric"><div class="metric-label">数据库</div><div class="metric-value ${d.health.database==='ok'?'good':'bad'}">${d.health.database==='ok'?'正常':'异常'}</div><div class="metric-foot">预测档案已连接</div></div><div class="metric"><div class="metric-label">AI 自动预测</div><div class="metric-value ${d.ai.auto_predict?'good':'warn'}">${d.ai.auto_predict?'已开启':'已关闭'}</div><div class="metric-foot">关闭不影响本机云端</div></div><div class="metric"><div class="metric-label">当前模型</div><div class="metric-value">${d.ai.profile_name?esc(d.ai.profile_name):'未选择'}</div><div class="metric-foot">已保存 ${d.ai_registry.profile_count||0} 个模型</div></div>`;$('adminLotteries').innerHTML=d.lotteries.map(lotteryCard).join('');$('diagnostics').innerHTML=diagnostics(d);$('aiAutoEnabled').checked=!!d.ai_registry.auto_predict;profiles(d.ai_registry);if(currentProfileId)selectProfile(currentProfileId);else if(d.ai_registry.active_profile_id)selectProfile(d.ai_registry.active_profile_id);$('recordsList').innerHTML=d.records.length?d.records.map(archive).join(''):'<div class="empty">暂无预测档案</div>'}
async function load(){try{render(await api('/admin/api/state'))}catch(e){toast(e.message,true)}}
function profilePayload(){return {name:$('aiProfileName').value.trim(),endpoint:$('aiEndpoint').value.trim(),model:$('aiModel').value.trim(),api_key:$('aiKey').value||null,timeout_seconds:Number($('aiTimeout').value),activate:false}}
function testPayload(){return {enabled:true,profile_id:currentProfileId,name:$('aiProfileName').value.trim(),endpoint:$('aiEndpoint').value.trim(),model:$('aiModel').value.trim(),api_key:$('aiKey').value||null,timeout_seconds:Number($('aiTimeout').value)}}
async function useProfile(id){try{await api('/admin/api/ai/profiles/'+encodeURIComponent(id)+'/activate',{method:'POST'});toast('已设为当前模型，从下一期开始使用');await load()}catch(e){toast(e.message,true)}}
$('newAiBtn').onclick=()=>{clearEditor();panel('ai')};$('saveAiBtn').onclick=async()=>{const b=$('saveAiBtn');b.disabled=true;try{const path=currentProfileId?'/admin/api/ai/profiles/'+encodeURIComponent(currentProfileId):'/admin/api/ai/profiles';const method=currentProfileId?'PUT':'POST';const d=await api(path,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(profilePayload())});currentProfileId=d.profile.id;$('aiKey').value='';toast(currentProfileId?'模型配置已保存':'模型已添加');await load()}catch(e){toast(e.message,true)}finally{b.disabled=false}};
$('activateAiBtn').onclick=async()=>{if(currentProfileId)await useProfile(currentProfileId)};$('deleteAiBtn').onclick=async()=>{if(!currentProfileId||!confirm('确定删除这个模型配置吗？'))return;try{await api('/admin/api/ai/profiles/'+encodeURIComponent(currentProfileId),{method:'DELETE'});toast('模型配置已删除');clearEditor();await load()}catch(e){toast(e.message,true)}};
$('aiAutoEnabled').onchange=async()=>{const enabled=$('aiAutoEnabled').checked;try{await api('/admin/api/ai/auto',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled})});toast(enabled?'AI 自动预测已开启':'AI 自动预测已关闭');await load()}catch(e){$('aiAutoEnabled').checked=!enabled;toast(e.message,true)}};
document.querySelectorAll('[data-preset]').forEach(b=>b.onclick=()=>{const p=b.dataset.preset;if(p==='deepseek-pro'){$('aiProfileName').value='DeepSeek V4 Pro';$('aiEndpoint').value='https://api.deepseek.com/chat/completions';$('aiModel').value='deepseek-v4-pro'}else if(p==='deepseek-flash'){$('aiProfileName').value='DeepSeek V4 Flash';$('aiEndpoint').value='https://api.deepseek.com/chat/completions';$('aiModel').value='deepseek-v4-flash'}else if(p==='deepseek-custom'){$('aiProfileName').value='DeepSeek 自定义';$('aiEndpoint').value='https://api.deepseek.com/chat/completions';$('aiModel').focus()}else{$('aiProfileName').value='OpenAI';$('aiEndpoint').value='https://api.openai.com/v1/responses';$('aiModel').value=''}});
$('testAiBtn').onclick=async()=>{const b=$('testAiBtn');b.disabled=true;try{$('aiResult').className='result';$('aiResult').textContent='正在真实调用当前填写的模型…';const d=await api('/admin/api/ai/test',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(testPayload())});$('aiResult').className='result success';$('aiResult').textContent='连接成功\n'+d.message+'\n耗时：'+d.latency_ms+' 毫秒';toast('模型真实调用成功')}catch(e){$('aiResult').className='result error';$('aiResult').textContent='测试失败\n'+friendlyError(e.message);toast(friendlyError(e.message),true)}finally{b.disabled=false}};
$('modelsBtn').onclick=async()=>{const b=$('modelsBtn');b.disabled=true;try{$('aiResult').className='result';$('aiResult').textContent='正在读取模型列表…';const d=await api('/admin/api/ai/models',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(testPayload())});$('modelList').innerHTML=(d.models||[]).map(m=>`<option value="${esc(m)}"></option>`).join('');$('aiResult').className='result success';$('aiResult').textContent='读取成功，共 '+(d.models||[]).length+' 个模型\n'+(d.models||[]).join('\n')}catch(e){$('aiResult').className='result error';$('aiResult').textContent='读取失败\n'+friendlyError(e.message)}finally{b.disabled=false}};
$('runBtn').onclick=async()=>{const b=$('runBtn');b.disabled=true;try{const d=await api('/admin/api/run',{method:'POST'});toast(d.message||'同步已开始');setTimeout(load,4500)}catch(e){toast(e.message,true)}finally{setTimeout(()=>b.disabled=false,2200)}};$('passwordBtn').onclick=async()=>{try{await api('/admin/api/password',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({current_password:$('oldPassword').value,new_password:$('newPassword').value})});$('oldPassword').value='';$('newPassword').value='';toast('管理密码已更新')}catch(e){toast(e.message,true)}};$('logoutBtn').onclick=async()=>{await api('/admin/api/logout',{method:'POST'}).catch(()=>{});location.href='/admin'};clearEditor();load();setInterval(load,30000);
"""
    return _document("天机控制台", body, script)
